- src/pycture/editor/__init__.py
- src/pycture/editor/container.py
- src/pycture/editor/data_bar.py
- src/pycture/editor/image.py
> Fix the data bar size

- src/pycture/commands/edit_commands.py
- src/pycture/commands/view_commands.py
- src/pycture/editor/__init__.py
- src/pycture/editor/image/__init__.py
- src/pycture/editor/image/color.py
- src/pycture/editor/image/image_loader.py
Closes #35 
Now the UX is much better, because the program doesn't freeze while loading an image
> Move image load computations to another thread

- src/pycture/editor/container.py
- src/pycture/editor/data_bar.py
- src/pycture/editor/image/__init__.py
> Add position to the data bar

- src/pycture/__init__.py
- src/pycture/commands/edit_commands/convert_to_gray_scale.py
- src/pycture/commands/edit_commands/transform_by_linear_segments.py
- src/pycture/commands/file_commands.py
- src/pycture/commands/view_commands/view_histogram.py
- src/pycture/editor/__init__.py
- src/pycture/editor/container.py
- src/pycture/editor/image/__init__.py
- src/pycture/editor/image/image_loader.py
- src/pycture/editor/image_holder.py
> Add Image holder

- src/pycture/dialogs/segments_input.py
- src/pycture/editor/image/__init__.py
- src/pycture/editor/image/color.py
- src/pycture/editor/image/image_loader.py
> Add RGBColor

- src/pycture/editor/image/__init__.py
- src/pycture/editor/image/image_loader.py
- src/pycture/editor/image/pixel.py
- src/pycture/editor/image_holder.py
> Move pixel operations to pixel class

- src/pycture/commands/view_commands/view_image_info.py
- src/pycture/dialogs/__init__.py
- src/pycture/dialogs/information_window.py
> Information window

- src/pycture/commands/__init__.py
- src/pycture/commands/edit_commands/__init__.py
- src/pycture/commands/edit_commands/equalize.py
- src/pycture/commands/edit_commands/transform_by_linear_segments.py
- src/pycture/editor/image/__init__.py
- src/pycture/menu_bar/command_menus.py
closes #38 
When this PR gets merged, it will be possible to equalize images
> Allow equalizing an image

- src/pycture/__init__.py
Now the main windows appear centered and with a better default size, which closes #78
> Better default size

- src/pycture/editor/container.py
- src/pycture/editor/image_holder.py
> Rubberband

- src/pycture/editor/image/__init__.py
- src/pycture/editor/image/color.py
- src/pycture/editor/image/get_rgb.py
- src/pycture/editor/image/image_loader.py
Now `Image.apply_LUTs`  is faster due to the use of `QImage.constBits()`
> Apply lut optimize

- src/pycture/commands/edit_commands/edit_brightness_and_contrast.py
- src/pycture/dialogs/edit_brightness_and_contrast.py
> Rgb editing

- src/pycture/commands/command.py
- src/pycture/commands/edit_commands/edit_brightness_and_contrast.py
- src/pycture/commands/edit_commands/gamma_correction.py
- src/pycture/commands/file_commands.py
- src/pycture/commands/help_commands.py
- src/pycture/commands/view_commands/view_difference.py
- src/pycture/dialogs/__init__.py
- src/pycture/dialogs/difference_dialog.py
- src/pycture/editor/container.py
- src/pycture/editor/image/__init__.py
- src/pycture/editor/image/image_loader.py
> Loading bar

- src/pycture/commands/edit_commands/transform_by_linear_segments.py
- src/pycture/commands/view_commands/view_difference.py
- src/pycture/commands/view_commands/view_histogram.py
- src/pycture/dialogs/plot_window.py
Scale setted for plots and some minor fixes
> Plot changes

- src/pycture/commands/view_commands/view_histogram.py
- src/pycture/css.py
- src/pycture/dialogs/plot_window.py
Not a lot could be done, but it's better now
> Improve the PlotWindow toolbar style

- src/pycture/commands/edit_commands/gamma_correction.py
- src/pycture/commands/edit_commands/transform_by_linear_segments.py
- src/pycture/dialogs/gamma_correction_dialog.py
- src/pycture/dialogs/widgets/__init__.py
- src/pycture/dialogs/widgets/custom_double_validator.py
> Gamma refactor

- src/pycture/__init__.py
- src/pycture/commands/__init__.py
- src/pycture/commands/view_commands/__init__.py
- src/pycture/commands/view_commands/view_difference.py
- src/pycture/commands/view_commands/view_map_of_changes.py
- src/pycture/dialogs/__init__.py
- src/pycture/dialogs/map_of_changes_dialog.py
- src/pycture/dialogs/select_two_images_dialog.py
- src/pycture/editor/__init__.py
- src/pycture/editor/image/__init__.py
> Interactive moc

- src/pycture/commands/edit_commands/gamma_correction.py
- src/pycture/commands/edit_commands/transform_by_linear_segments.py
- src/pycture/dialogs/gamma_correction_dialog.py
- src/pycture/dialogs/segments_input.py
> Add dropdowns

- src/pycture/__init__.py
- src/pycture/commands/edit_commands/gamma_correction.py
- src/pycture/commands/edit_commands/transform_by_linear_segments.py
- src/pycture/dialogs/gamma_correction_dialog.py
- src/pycture/dialogs/segments_input.py
- src/pycture/dialogs/widgets/point_input.py
- src/pycture/dialogs/widgets/points_input.py
- src/pycture/editor/container.py
> Dialog with plots

- src/pycture/commands/view_commands/view_histogram.py
- src/pycture/dialogs/plot_window.py
> Correctly handle histogram plt figures

- src/pycture/commands/view_commands/view_difference.py
- src/pycture/commands/view_commands/view_map_of_changes.py
- src/pycture/dialogs/map_of_changes_dialog.py
- src/pycture/dialogs/plot_window.py
- src/pycture/dialogs/select_two_images_dialog.py
- src/pycture/dialogs/widgets/dropdown_list.py
Histograms of the difference image are now shown within the Map of Changes dialog
> Map of changes histogram

- src/pycture/commands/edit_commands/interpolation.py
- src/pycture/commands/edit_commands/scale.py
- src/pycture/editor/image/__init__.py
- src/pycture/editor/image/get_argb.py
- src/pycture/editor/image/get_rgb.py
- src/pycture/editor/image/image_loader.py
Closes #114 
This PR also makes Pycture start taking into account transparencies and trying to preserve them between changes
> Add transparency to rotated backgrounds

- src/pycture/commands/__init__.py
- src/pycture/commands/edit_commands/__init__.py
- src/pycture/commands/edit_commands/rotate_clockwise.py
- src/pycture/commands/edit_commands/transpose.py
- src/pycture/editor/image/__init__.py
> Add transpose and 90º rotations

- Pipfile
- Pipfile.lock
- src/pycture/commands/__init__.py
- src/pycture/commands/edit_commands/__init__.py
- src/pycture/commands/edit_commands/rotate.py
- src/pycture/commands/edit_commands/rotate_simple.py
- src/pycture/dialogs/__init__.py
- src/pycture/dialogs/rotate_simple_dialog.py
- src/pycture/editor/image/__init__.py
> Simple rotation (Rotate & paint)
